- op: remove
  path: /spec/template/spec/containers/0/resources
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: IfNotPresent
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: CERT_GENERATOR_IMAGE
    value: quay.io/modh/ray:2.44.1-py311-cu121
